name: Build and Deploy
on:
  push:
   branches:
     - main

jobs:
  build-and-deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout main
       uses: actions/checkout@v3.5.3

     - name: Install need and Build MARYTWIKI
       run: |
         npm install yarn -g
         yarn install
         yarn build
       env:
         NODE_OPTIONS: '--max_old_space_size=4096'

     - name: Deploy pages
       uses: JamesIves/github-pages-deploy-action@v4.4.3
       with:
         BRANCH: gh-pages
         FOLDER: docs/.vuepress/dist
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       
